// Broadsheet design tokens — DM Serif Display / IBM Plex Serif / IBM Plex Mono.
// Mirrors the inline `S` object from the original artifact so the visual
// language ports faithfully.

import type { CSSProperties } from 'react';

const mono = "'IBM Plex Mono', monospace";
const serif = "'IBM Plex Serif', Georgia, serif";
const display = "'DM Serif Display', serif";

export const COLORS = {
  paper: '#f3ecdc',
  panel: '#fbf7ec',
  ink: '#1a1814',
  inkDim: '#5f5a4d',
  rule: 'rgba(26,24,20,0.13)',
  red: '#9b2c2c',
  green: '#2e4c38',
  gold: '#9a7b2b',
  cream: '#e8dfc9',
};

export const S: Record<string, any> = {
  shell: { minHeight: '100vh', background: COLORS.paper, color: COLORS.ink, fontFamily: serif, backgroundImage: 'radial-gradient(rgba(26, 24, 20, 0.04) 1px, transparent 1px)', backgroundSize: '3px 3px' } as CSSProperties,
  masthead: { borderBottom: `3px double ${COLORS.ink}`, padding: '18px 24px 14px', background: COLORS.panel, position: 'relative' } as CSSProperties,
  mastheadInner: { maxWidth: 1400, margin: '0 auto', display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'baseline', gap: 16 } as CSSProperties,
  mastheadTitle: { fontFamily: display, fontSize: 38, letterSpacing: '0.01em', fontWeight: 400, lineHeight: 1, textAlign: 'center' } as CSSProperties,
  mastheadSub: { fontFamily: mono, fontSize: 10, letterSpacing: '0.25em', textTransform: 'uppercase', textAlign: 'center', marginTop: 6, color: COLORS.inkDim } as CSSProperties,
  mastheadMeta: { fontFamily: mono, fontSize: 10, letterSpacing: '0.12em', textTransform: 'uppercase', color: COLORS.inkDim } as CSSProperties,
  nav: { background: COLORS.cream, borderBottom: `1px solid ${COLORS.ink}`, padding: '0 24px', overflow: 'hidden' } as CSSProperties,
  navInner: { maxWidth: 1400, margin: '0 auto', display: 'flex', overflowX: 'auto' } as CSSProperties,
  navItem: (active: boolean): CSSProperties => ({
    padding: '10px 16px',
    fontFamily: mono,
    fontSize: 10.5,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    background: active ? COLORS.ink : 'transparent',
    color: active ? COLORS.paper : '#2d2a24',
    border: 'none',
    borderRight: `1px solid ${COLORS.rule}`,
  }),
  page: { maxWidth: 1400, margin: '0 auto', padding: '20px 24px 100px', width: '100%', boxSizing: 'border-box' } as CSSProperties,
  footer: { position: 'sticky', bottom: 0, background: COLORS.ink, color: COLORS.paper, borderTop: `3px double ${COLORS.paper}`, padding: '10px 24px', zIndex: 10 } as CSSProperties,
  footerInner: { maxWidth: 1400, margin: '0 auto', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' } as CSSProperties,
  footerDate: { fontFamily: display, fontSize: 18 } as CSSProperties,
  footerPhase: { fontFamily: mono, fontSize: 10, letterSpacing: '0.2em', textTransform: 'uppercase', color: COLORS.cream, padding: '3px 9px', border: `1px solid ${COLORS.cream}` } as CSSProperties,
  footerBtn: { padding: '7px 12px', fontFamily: mono, fontSize: 10, letterSpacing: '0.15em', textTransform: 'uppercase', border: `1px solid ${COLORS.paper}`, color: COLORS.paper, background: 'transparent', cursor: 'pointer' } as CSSProperties,
  footerBtnPrimary: { padding: '8px 14px', fontFamily: mono, fontSize: 10.5, letterSpacing: '0.15em', textTransform: 'uppercase', border: `1px solid ${COLORS.paper}`, color: COLORS.ink, background: COLORS.paper, cursor: 'pointer', fontWeight: 600 } as CSSProperties,
  sectionHead: { fontFamily: display, fontSize: 28, marginBottom: 4, lineHeight: 1.1 } as CSSProperties,
  sectionSub: { fontFamily: mono, fontSize: 10, letterSpacing: '0.25em', textTransform: 'uppercase', color: COLORS.inkDim, marginTop: 2 } as CSSProperties,
  sectionRule: { borderBottom: `3px double ${COLORS.ink}`, paddingBottom: 10, marginBottom: 20 } as CSSProperties,
  eyebrow: { fontFamily: mono, fontSize: 9.5, letterSpacing: '0.28em', textTransform: 'uppercase', color: COLORS.inkDim, marginBottom: 4 } as CSSProperties,
  panel: { background: COLORS.panel, border: `1px solid ${COLORS.ink}`, padding: '16px 18px' } as CSSProperties,
  panelThick: { background: COLORS.panel, border: `2px solid ${COLORS.ink}`, padding: '16px 18px' } as CSSProperties,
  panelTitle: { fontFamily: mono, fontSize: 10, letterSpacing: '0.22em', textTransform: 'uppercase', color: COLORS.inkDim, borderBottom: `1px solid ${COLORS.rule}`, paddingBottom: 6, marginBottom: 12 } as CSSProperties,
  stat: { background: COLORS.panel, border: `1px solid ${COLORS.ink}`, padding: '14px 16px' } as CSSProperties,
  statLabel: { fontFamily: mono, fontSize: 9.5, letterSpacing: '0.25em', textTransform: 'uppercase', color: COLORS.inkDim } as CSSProperties,
  statValue: { fontFamily: display, fontSize: 28, lineHeight: 1.1, fontVariantNumeric: 'tabular-nums', marginTop: 4 } as CSSProperties,
  statDelta: { fontFamily: mono, fontSize: 11, marginTop: 2, color: COLORS.inkDim } as CSSProperties,
  divider: { borderBottom: `3px double ${COLORS.ink}`, margin: '20px 0' } as CSSProperties,
  badge: { display: 'inline-block', padding: '2px 7px', fontFamily: mono, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', border: `1px solid ${COLORS.ink}`, background: COLORS.panel } as CSSProperties,
  badgeRed: { background: COLORS.red, color: COLORS.paper, borderColor: COLORS.red } as CSSProperties,
  badgeGreen: { background: COLORS.green, color: COLORS.paper, borderColor: COLORS.green } as CSSProperties,
  badgeGold: { background: COLORS.gold, color: COLORS.paper, borderColor: COLORS.gold } as CSSProperties,
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 } as CSSProperties,
  th: { fontFamily: mono, fontSize: 9.5, letterSpacing: '0.2em', textTransform: 'uppercase', color: COLORS.inkDim, padding: '8px 10px', borderBottom: `2px solid ${COLORS.ink}`, textAlign: 'left', fontWeight: 500 } as CSSProperties,
  thNum: { textAlign: 'right' } as CSSProperties,
  td: { padding: '7px 10px', borderBottom: `1px solid ${COLORS.rule}` } as CSSProperties,
  tdNum: { textAlign: 'right', fontVariantNumeric: 'tabular-nums', fontFamily: mono, fontSize: 12 } as CSSProperties,
  tdName: { fontFamily: serif, fontWeight: 500 } as CSSProperties,
  tdPos: { fontFamily: mono, fontSize: 10, color: COLORS.inkDim, letterSpacing: '0.1em' } as CSSProperties,
  radioBtn: (active: boolean): CSSProperties => ({
    padding: '9px 14px',
    border: `1px solid ${COLORS.ink}`,
    background: active ? COLORS.ink : COLORS.panel,
    color: active ? COLORS.paper : COLORS.ink,
    fontFamily: mono,
    fontSize: 10,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  }),
  franchiseCard: (selected: boolean): CSSProperties => ({
    border: selected ? `2px solid ${COLORS.red}` : `2px solid ${COLORS.ink}`,
    background: selected ? '#f8f2e4' : COLORS.panel,
    padding: 12,
    cursor: 'pointer',
    textAlign: 'center',
    outline: selected ? `1px solid ${COLORS.red}` : 'none',
  }),
  ledger: { width: '100%', borderCollapse: 'collapse', fontFamily: mono, fontSize: 13 } as CSSProperties,
  ledgerTd: { padding: '6px 12px', borderBottom: `1px dotted ${COLORS.rule}` } as CSSProperties,
  ledgerTdNum: { padding: '6px 12px', borderBottom: `1px dotted ${COLORS.rule}`, textAlign: 'right', fontVariantNumeric: 'tabular-nums' } as CSSProperties,
  ledgerDivider: { borderBottom: `2px solid ${COLORS.ink}`, paddingTop: 8, paddingBottom: 4, fontFamily: mono, fontSize: 10, letterSpacing: '0.2em', textTransform: 'uppercase', color: COLORS.inkDim } as CSSProperties,
  ledgerTotal: { borderTop: `2px solid ${COLORS.ink}`, borderBottom: `3px double ${COLORS.ink}`, paddingTop: 10, paddingBottom: 10, fontFamily: display, fontSize: 18 } as CSSProperties,
  debit: { color: COLORS.red } as CSSProperties,
  headlineXL: { fontFamily: display, fontSize: 52, lineHeight: 1, letterSpacing: '-0.01em' } as CSSProperties,
  headlineLG: { fontFamily: display, fontSize: 34, lineHeight: 1.05 } as CSSProperties,
  headlineMD: { fontFamily: display, fontSize: 22, lineHeight: 1.1 } as CSSProperties,
  byline: { fontFamily: serif, fontStyle: 'italic', color: COLORS.inkDim } as CSSProperties,
};
