// Broadsheet design tokens — DM Serif Display / IBM Plex Serif / IBM Plex Mono.
// Mirrors the inline `S` object from the original artifact so the visual
// language ports faithfully.
const mono = "'IBM Plex Mono', monospace";
const serif = "'IBM Plex Serif', Georgia, serif";
const display = "'DM Serif Display', serif";
export const COLORS = {
    paper: '#f3ecdc',
    panel: '#fbf7ec',
    ink: '#1a1814',
    inkDim: '#5f5a4d',
    rule: 'rgba(26,24,20,0.13)',
    red: '#9b2c2c',
    green: '#2e4c38',
    gold: '#9a7b2b',
    cream: '#e8dfc9',
};
export const S = {
    shell: { minHeight: '100vh', background: COLORS.paper, color: COLORS.ink, fontFamily: serif, backgroundImage: 'radial-gradient(rgba(26, 24, 20, 0.04) 1px, transparent 1px)', backgroundSize: '3px 3px' },
    masthead: { borderBottom: `3px double ${COLORS.ink}`, padding: '18px 24px 14px', background: COLORS.panel, position: 'relative' },
    mastheadInner: { maxWidth: 1400, margin: '0 auto', display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'baseline', gap: 16 },
    mastheadTitle: { fontFamily: display, fontSize: 38, letterSpacing: '0.01em', fontWeight: 400, lineHeight: 1, textAlign: 'center' },
    mastheadSub: { fontFamily: mono, fontSize: 10, letterSpacing: '0.25em', textTransform: 'uppercase', textAlign: 'center', marginTop: 6, color: COLORS.inkDim },
    mastheadMeta: { fontFamily: mono, fontSize: 10, letterSpacing: '0.12em', textTransform: 'uppercase', color: COLORS.inkDim },
    nav: { background: COLORS.cream, borderBottom: `1px solid ${COLORS.ink}`, padding: '0 24px', overflow: 'hidden' },
    navInner: { maxWidth: 1400, margin: '0 auto', display: 'flex', overflowX: 'auto' },
    navItem: (active) => ({
        padding: '10px 16px',
        fontFamily: mono,
        fontSize: 10.5,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        whiteSpace: 'nowrap',
        cursor: 'pointer',
        background: active ? COLORS.ink : 'transparent',
        color: active ? COLORS.paper : '#2d2a24',
        border: 'none',
        borderRight: `1px solid ${COLORS.rule}`,
    }),
    page: { maxWidth: 1400, margin: '0 auto', padding: '20px 24px 100px', width: '100%', boxSizing: 'border-box' },
    footer: { position: 'sticky', bottom: 0, background: COLORS.ink, color: COLORS.paper, borderTop: `3px double ${COLORS.paper}`, padding: '10px 24px', zIndex: 10 },
    footerInner: { maxWidth: 1400, margin: '0 auto', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
    footerDate: { fontFamily: display, fontSize: 18 },
    footerPhase: { fontFamily: mono, fontSize: 10, letterSpacing: '0.2em', textTransform: 'uppercase', color: COLORS.cream, padding: '3px 9px', border: `1px solid ${COLORS.cream}` },
    footerBtn: { padding: '7px 12px', fontFamily: mono, fontSize: 10, letterSpacing: '0.15em', textTransform: 'uppercase', border: `1px solid ${COLORS.paper}`, color: COLORS.paper, background: 'transparent', cursor: 'pointer' },
    footerBtnPrimary: { padding: '8px 14px', fontFamily: mono, fontSize: 10.5, letterSpacing: '0.15em', textTransform: 'uppercase', border: `1px solid ${COLORS.paper}`, color: COLORS.ink, background: COLORS.paper, cursor: 'pointer', fontWeight: 600 },
    sectionHead: { fontFamily: display, fontSize: 28, marginBottom: 4, lineHeight: 1.1 },
    sectionSub: { fontFamily: mono, fontSize: 10, letterSpacing: '0.25em', textTransform: 'uppercase', color: COLORS.inkDim, marginTop: 2 },
    sectionRule: { borderBottom: `3px double ${COLORS.ink}`, paddingBottom: 10, marginBottom: 20 },
    eyebrow: { fontFamily: mono, fontSize: 9.5, letterSpacing: '0.28em', textTransform: 'uppercase', color: COLORS.inkDim, marginBottom: 4 },
    panel: { background: COLORS.panel, border: `1px solid ${COLORS.ink}`, padding: '16px 18px' },
    panelThick: { background: COLORS.panel, border: `2px solid ${COLORS.ink}`, padding: '16px 18px' },
    panelTitle: { fontFamily: mono, fontSize: 10, letterSpacing: '0.22em', textTransform: 'uppercase', color: COLORS.inkDim, borderBottom: `1px solid ${COLORS.rule}`, paddingBottom: 6, marginBottom: 12 },
    stat: { background: COLORS.panel, border: `1px solid ${COLORS.ink}`, padding: '14px 16px' },
    statLabel: { fontFamily: mono, fontSize: 9.5, letterSpacing: '0.25em', textTransform: 'uppercase', color: COLORS.inkDim },
    statValue: { fontFamily: display, fontSize: 28, lineHeight: 1.1, fontVariantNumeric: 'tabular-nums', marginTop: 4 },
    statDelta: { fontFamily: mono, fontSize: 11, marginTop: 2, color: COLORS.inkDim },
    divider: { borderBottom: `3px double ${COLORS.ink}`, margin: '20px 0' },
    badge: { display: 'inline-block', padding: '2px 7px', fontFamily: mono, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', border: `1px solid ${COLORS.ink}`, background: COLORS.panel },
    badgeRed: { background: COLORS.red, color: COLORS.paper, borderColor: COLORS.red },
    badgeGreen: { background: COLORS.green, color: COLORS.paper, borderColor: COLORS.green },
    badgeGold: { background: COLORS.gold, color: COLORS.paper, borderColor: COLORS.gold },
    table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
    th: { fontFamily: mono, fontSize: 9.5, letterSpacing: '0.2em', textTransform: 'uppercase', color: COLORS.inkDim, padding: '8px 10px', borderBottom: `2px solid ${COLORS.ink}`, textAlign: 'left', fontWeight: 500 },
    thNum: { textAlign: 'right' },
    td: { padding: '7px 10px', borderBottom: `1px solid ${COLORS.rule}` },
    tdNum: { textAlign: 'right', fontVariantNumeric: 'tabular-nums', fontFamily: mono, fontSize: 12 },
    tdName: { fontFamily: serif, fontWeight: 500 },
    tdPos: { fontFamily: mono, fontSize: 10, color: COLORS.inkDim, letterSpacing: '0.1em' },
    radioBtn: (active) => ({
        padding: '9px 14px',
        border: `1px solid ${COLORS.ink}`,
        background: active ? COLORS.ink : COLORS.panel,
        color: active ? COLORS.paper : COLORS.ink,
        fontFamily: mono,
        fontSize: 10,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        cursor: 'pointer',
    }),
    franchiseCard: (selected) => ({
        border: selected ? `2px solid ${COLORS.red}` : `2px solid ${COLORS.ink}`,
        background: selected ? '#f8f2e4' : COLORS.panel,
        padding: 12,
        cursor: 'pointer',
        textAlign: 'center',
        outline: selected ? `1px solid ${COLORS.red}` : 'none',
    }),
    ledger: { width: '100%', borderCollapse: 'collapse', fontFamily: mono, fontSize: 13 },
    ledgerTd: { padding: '6px 12px', borderBottom: `1px dotted ${COLORS.rule}` },
    ledgerTdNum: { padding: '6px 12px', borderBottom: `1px dotted ${COLORS.rule}`, textAlign: 'right', fontVariantNumeric: 'tabular-nums' },
    ledgerDivider: { borderBottom: `2px solid ${COLORS.ink}`, paddingTop: 8, paddingBottom: 4, fontFamily: mono, fontSize: 10, letterSpacing: '0.2em', textTransform: 'uppercase', color: COLORS.inkDim },
    ledgerTotal: { borderTop: `2px solid ${COLORS.ink}`, borderBottom: `3px double ${COLORS.ink}`, paddingTop: 10, paddingBottom: 10, fontFamily: display, fontSize: 18 },
    debit: { color: COLORS.red },
    headlineXL: { fontFamily: display, fontSize: 52, lineHeight: 1, letterSpacing: '-0.01em' },
    headlineLG: { fontFamily: display, fontSize: 34, lineHeight: 1.05 },
    headlineMD: { fontFamily: display, fontSize: 22, lineHeight: 1.1 },
    byline: { fontFamily: serif, fontStyle: 'italic', color: COLORS.inkDim },
};
