import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { S, COLORS } from '../styles/tokens';
import { useGame } from '../state/store';
import { FRANCHISES } from '../engine/franchises';
import { fmtShort, ratingClass, toScout } from '../engine/format';
import { streakLabel } from '../engine/streaks';
import { RatingBar } from '../components/RatingBar';
import { PayrollBar } from '../components/PayrollBar';
import { RosterShortfallAlert } from '../components/RosterShortfallAlert';
export function Roster() {
    const { state, waivePlayerAction, setSelectedPlayerId } = useGame();
    const [selected, setSelected] = useState(null);
    if (!state)
        return null;
    const fid = state.userFranchiseId;
    const f = FRANCHISES[fid];
    const players = state.rosters[fid].map((id) => state.players[id]);
    const hitters = players.filter((p) => !p.isPitcher).sort((a, b) => b.ratings.overall - a.ratings.overall);
    const pitchers = players.filter((p) => p.isPitcher).sort((a, b) => b.ratings.overall - a.ratings.overall);
    return (_jsxs("div", { children: [_jsxs("div", { style: S.sectionRule, children: [_jsxs("h2", { style: S.sectionHead, children: [f.city, " ", f.name, " Roster"] }), _jsxs("div", { style: S.sectionSub, children: [players.length, " players on the active roster"] })] }), _jsx(RosterShortfallAlert, {}), _jsx("div", { style: { marginBottom: 16 }, children: _jsx(PayrollBar, {}) }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: selected ? '2fr 1fr' : '1fr', gap: 16 }, children: [_jsxs("div", { children: [_jsxs("div", { style: S.panel, children: [_jsx("div", { style: S.panelTitle, children: "Position Players" }), _jsxs("table", { style: S.table, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { style: S.th, children: "Pos" }), _jsx("th", { style: S.th, children: "Name" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "Age" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "OVR" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "POT" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "Salary" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "Yrs" }), _jsx("th", { style: S.th, children: "Streak" }), _jsx("th", { style: S.th, children: "Status" })] }) }), _jsx("tbody", { children: hitters.map((p) => (_jsxs("tr", { style: { cursor: 'pointer', background: selected === p.id ? '#f8f2e4' : 'transparent' }, onClick: () => setSelected(p.id), children: [_jsx("td", { style: { ...S.td, ...S.tdPos }, children: p.pos }), _jsxs("td", { style: { ...S.td, ...S.tdName }, children: [p.firstName, " ", p.lastName] }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: p.age }), _jsx("td", { style: { ...S.td, ...S.tdNum, color: ratingClass(p.ratings.overall), fontWeight: 600 }, children: toScout(p.ratings.overall) }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: toScout(p.potential) }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: p.contract ? fmtShort(p.contract.salary) : '-' }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: p.contract?.years ?? '-' }), _jsx("td", { style: { ...S.td, fontFamily: "'IBM Plex Mono', monospace", fontSize: 11 }, children: streakLabel(p.streakMod) }), _jsx("td", { style: S.td, children: p.health === 'healthy'
                                                                ? _jsx("span", { style: { ...S.badge, ...S.badgeGreen }, children: "Active" })
                                                                : _jsx("span", { style: { ...S.badge, ...S.badgeRed }, children: p.health.toUpperCase() }) })] }, p.id))) })] })] }), _jsxs("div", { style: { marginTop: 16, ...S.panel }, children: [_jsx("div", { style: S.panelTitle, children: "Pitching Staff" }), _jsxs("table", { style: S.table, children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { style: S.th, children: "Pos" }), _jsx("th", { style: S.th, children: "Name" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "Age" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "OVR" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "Velo" }), _jsx("th", { style: { ...S.th, ...S.thNum }, children: "Salary" }), _jsx("th", { style: S.th, children: "Status" })] }) }), _jsx("tbody", { children: pitchers.map((p) => (_jsxs("tr", { style: { cursor: 'pointer', background: selected === p.id ? '#f8f2e4' : 'transparent' }, onClick: () => setSelected(p.id), children: [_jsx("td", { style: { ...S.td, ...S.tdPos }, children: p.pos }), _jsxs("td", { style: { ...S.td, ...S.tdName }, children: [p.firstName, " ", p.lastName] }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: p.age }), _jsx("td", { style: { ...S.td, ...S.tdNum, color: ratingClass(p.ratings.overall), fontWeight: 600 }, children: toScout(p.ratings.overall) }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: p.ratings.velo ?? '-' }), _jsx("td", { style: { ...S.td, ...S.tdNum }, children: p.contract ? fmtShort(p.contract.salary) : '-' }), _jsx("td", { style: S.td, children: p.health === 'healthy'
                                                                ? _jsx("span", { style: { ...S.badge, ...S.badgeGreen }, children: "Active" })
                                                                : _jsx("span", { style: { ...S.badge, ...S.badgeRed }, children: p.health.toUpperCase() }) })] }, p.id))) })] })] })] }), selected && (() => {
                        const p = state.players[selected];
                        if (!p)
                            return null;
                        return (_jsxs("div", { style: S.panel, children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [_jsx("div", { style: S.panelTitle, children: "Player Detail" }), _jsx("button", { onClick: () => setSelected(null), style: { background: 'none', border: 'none', cursor: 'pointer', color: COLORS.inkDim }, children: "x" })] }), _jsxs("div", { style: { fontFamily: "'DM Serif Display', serif", fontSize: 22, cursor: 'pointer', textDecoration: 'underline', color: COLORS.red }, onClick: () => setSelectedPlayerId(p.id), children: [p.firstName, " ", p.lastName] }), _jsxs("div", { style: S.byline, children: [p.pos, " - Age ", p.age, " - ", p.nat] }), _jsxs("div", { style: { marginTop: 12 }, children: [p.isPitcher ? (_jsxs(_Fragment, { children: [_jsx(RatingBar, { label: "Fastball", v: p.ratings.fastball }), _jsx(RatingBar, { label: "Breaking", v: p.ratings.breaking }), _jsx(RatingBar, { label: "Changeup", v: p.ratings.changeup }), _jsx(RatingBar, { label: "Command", v: p.ratings.command }), _jsx(RatingBar, { label: "Movement", v: p.ratings.movement }), _jsx(RatingBar, { label: "Stamina", v: p.ratings.stamina })] })) : (_jsxs(_Fragment, { children: [_jsx(RatingBar, { label: "Contact", v: p.ratings.contact }), _jsx(RatingBar, { label: "Power", v: p.ratings.power }), _jsx(RatingBar, { label: "Eye", v: p.ratings.eye }), _jsx(RatingBar, { label: "Speed", v: p.ratings.speed }), _jsx(RatingBar, { label: "Fielding", v: p.ratings.fielding }), _jsx(RatingBar, { label: "Arm", v: p.ratings.arm })] })), _jsxs("div", { style: { borderTop: `1px solid ${COLORS.rule}`, marginTop: 8, paddingTop: 8 }, children: [_jsx(RatingBar, { label: "Overall", v: p.ratings.overall }), _jsx(RatingBar, { label: "Potential", v: p.potential })] })] }), _jsx("div", { style: { marginTop: 12 }, children: _jsx("button", { onClick: () => {
                                            if (confirm(`Designate ${p.firstName} ${p.lastName} for assignment? Eats 50% of remaining contract.`)) {
                                                const r = waivePlayerAction(p.id);
                                                if (r.ok)
                                                    setSelected(null);
                                                else
                                                    alert(r.reason);
                                            }
                                        }, style: { ...S.radioBtn(true), background: COLORS.red, borderColor: COLORS.red, fontSize: 11 }, children: "DFA" }) }), p.injury && (_jsxs("div", { style: { marginTop: 12 }, children: [_jsx("div", { style: S.eyebrow, children: "Injury Status" }), _jsx("div", { style: { ...S.badge, ...S.badgeRed }, children: p.injury.severity.toUpperCase() }), _jsxs("div", { style: { marginTop: 4, fontSize: 12 }, children: [p.injury.type, " - back day ", p.injury.recoversOn] })] }))] }));
                    })()] })] }));
}
