import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { S, COLORS } from '../styles/tokens';
import { useGame } from '../state/store';
import { FRANCHISES } from '../engine/franchises';
import { fmt, fmtShort } from '../engine/format';
import { Inline } from '../components/Stat';
import { newParkCost } from '../engine/stadiumReplace';
export function Stadium() {
    const { state, purchaseUpgradeAction, buildStadiumAction, relocateAction } = useGame();
    const [showBuild, setShowBuild] = useState(false);
    const [showReloc, setShowReloc] = useState(false);
    const [parkName, setParkName] = useState('Maverick Park');
    const [parkCap, setParkCap] = useState(42000);
    const [parkPrem, setParkPrem] = useState(3500);
    const [parkAmen, setParkAmen] = useState(4);
    const [parkPf, setParkPf] = useState(102);
    const [relocCity, setRelocCity] = useState('Las Vegas');
    const [relocName, setRelocName] = useState('Mavericks');
    const [relocAbbr, setRelocAbbr] = useState('LV');
    const [relocColor, setRelocColor] = useState('#1f3a5f');
    if (!state)
        return null;
    const fid = state.userFranchiseId;
    const f = FRANCHISES[fid];
    const fin = state.finances[fid];
    const l = fin.ledger;
    const avgAtt = l.homeGames > 0 ? Math.round(l.attendance / l.homeGames) : 0;
    return (_jsxs("div", { children: [_jsxs("div", { style: S.sectionRule, children: [_jsx("h2", { style: S.sectionHead, children: f.park }), _jsxs("div", { style: S.sectionSub, children: [f.city, " \u00B7 capacity ", fmt(f.cap)] })] }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }, children: [_jsxs("div", { style: S.panel, children: [_jsx("div", { style: S.panelTitle, children: "Ballpark" }), _jsx(Inline, { label: "Capacity", value: fmt(f.cap) }), _jsx(Inline, { label: "Premium Seats", value: fmt(f.premium) }), _jsx(Inline, { label: "Park Factor", value: f.pf }), _jsx(Inline, { label: "Amenity Tier", value: `${f.amen} / 5` }), _jsx(Inline, { label: "Naming Rights", value: fin.nameRightsValue > 0 ? `${fmtShort(fin.nameRightsValue)}/yr (${fin.nameRightsYearsLeft} yrs)` : 'None' })] }), _jsxs("div", { style: S.panel, children: [_jsx("div", { style: S.panelTitle, children: "This Season" }), _jsx(Inline, { label: "Home Games", value: fmt(l.homeGames) }), _jsx(Inline, { label: "Total Attendance", value: fmt(l.attendance) }), _jsx(Inline, { label: "Avg Attendance", value: fmt(avgAtt) }), _jsx(Inline, { label: "Gate Revenue", value: fmtShort(l.ticketRev + l.premiumRev) }), _jsx(Inline, { label: "Concessions", value: fmtShort(l.concRev) }), _jsx(Inline, { label: "Parking", value: fmtShort(l.parkRev) }), _jsx(Inline, { label: "Merchandise", value: fmtShort(l.merchRev) })] })] }), _jsxs("div", { style: { marginTop: 16, ...S.panel }, children: [_jsx("div", { style: S.panelTitle, children: "Stadium Upgrades" }), _jsx("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }, children: ([
                            { t: 'capacity', title: 'Expand Capacity', desc: '+2,000 seats', cost: 80, hint: 'Higher gate revenue ceiling.' },
                            { t: 'premium', title: 'Premium Seating', desc: '+500 premium', cost: 40, hint: 'Premium seats sell at ~4× ticket price.' },
                            { t: 'amenity', title: 'Amenity Tier', desc: f.amen >= 5 ? 'Maxed' : `+1 (now ${f.amen}/5)`, cost: 60, hint: 'Boosts concessions, merch, and fan demand.' },
                        ]).map((up) => (_jsxs("div", { style: S.stat, children: [_jsx("div", { style: S.statLabel, children: up.title }), _jsxs("div", { style: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 13, marginTop: 4 }, children: [up.desc, " \u00B7 $", up.cost, "M"] }), _jsx("div", { style: { ...S.byline, fontSize: 12, marginTop: 4 }, children: up.hint }), _jsx("button", { onClick: () => {
                                        const r = purchaseUpgradeAction(up.t);
                                        if (r.ok)
                                            alert(`${up.title} complete.`);
                                        else
                                            alert(r.reason || 'Failed');
                                    }, disabled: fin.teamCash < up.cost * 1_000_000 || (up.t === 'amenity' && f.amen >= 5), style: {
                                        ...S.radioBtn(true), marginTop: 8,
                                        background: fin.teamCash >= up.cost * 1_000_000 && !(up.t === 'amenity' && f.amen >= 5) ? COLORS.green : '#999',
                                        borderColor: fin.teamCash >= up.cost * 1_000_000 && !(up.t === 'amenity' && f.amen >= 5) ? COLORS.green : '#999',
                                        cursor: fin.teamCash >= up.cost * 1_000_000 && !(up.t === 'amenity' && f.amen >= 5) ? 'pointer' : 'not-allowed',
                                        width: '100%',
                                    }, children: "Purchase" })] }, up.t))) })] }), _jsxs("div", { style: { marginTop: 16, ...S.panel }, children: [_jsx("div", { style: S.panelTitle, children: "Color Identity" }), _jsxs("div", { style: { display: 'flex', gap: 6, alignItems: 'center' }, children: [_jsx("div", { style: { width: 80, height: 30, background: f.color, border: `1px solid ${COLORS.ink}` } }), _jsx("span", { style: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12 }, children: f.color }), f.secondaryColor && _jsxs(_Fragment, { children: [_jsx("div", { style: { width: 80, height: 30, background: f.secondaryColor, border: `1px solid ${COLORS.ink}`, marginLeft: 12 } }), _jsx("span", { style: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12 }, children: f.secondaryColor })] })] })] }), _jsxs("div", { style: { marginTop: 16, ...S.panel }, children: [_jsx("div", { style: S.panelTitle, children: "Build a New Ballpark" }), _jsxs("div", { style: S.byline, children: ["A complete replacement: new capacity, premium seats, amenities, and park factors. Estimated cost ", fmtShort(newParkCost({ name: parkName, cap: parkCap, premium: parkPrem, amen: parkAmen, pf: parkPf })), "."] }), _jsx("button", { onClick: () => setShowBuild((v) => !v), style: { ...S.radioBtn(showBuild), marginTop: 6 }, children: showBuild ? 'Hide builder' : 'Open builder' }), showBuild && (_jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginTop: 12 }, children: [_jsxs("label", { style: { ...S.eyebrow }, children: ["Name", _jsx("input", { value: parkName, onChange: (e) => setParkName(e.target.value), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Capacity", _jsx("input", { type: "number", value: parkCap, onChange: (e) => setParkCap(Number(e.target.value)), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Premium", _jsx("input", { type: "number", value: parkPrem, onChange: (e) => setParkPrem(Number(e.target.value)), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Amenity (1-5)", _jsx("input", { type: "number", min: 1, max: 5, value: parkAmen, onChange: (e) => setParkAmen(Math.max(1, Math.min(5, Number(e.target.value)))), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Park Factor (95-115)", _jsx("input", { type: "number", min: 95, max: 115, value: parkPf, onChange: (e) => setParkPf(Math.max(95, Math.min(115, Number(e.target.value)))), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsx("button", { onClick: () => {
                                    const r = buildStadiumAction({ name: parkName, cap: parkCap, premium: parkPrem, amen: parkAmen, pf: parkPf });
                                    alert(r.ok ? `${parkName} ready for opening day!` : (r.reason || 'Failed'));
                                }, style: { ...S.radioBtn(true), background: COLORS.red, borderColor: COLORS.red }, children: "Build" })] }))] }), _jsxs("div", { style: { marginTop: 16, ...S.panel }, children: [_jsx("div", { style: S.panelTitle, children: "Relocate / Rebrand Franchise" }), _jsx("div", { style: S.byline, children: "Move the team to a new city with a new identity. $500M relocation fee. Triggers a 3-year market reset." }), _jsx("button", { onClick: () => setShowReloc((v) => !v), style: { ...S.radioBtn(showReloc), marginTop: 6 }, children: showReloc ? 'Hide relocation' : 'Open relocation' }), showReloc && (_jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 8, marginTop: 12 }, children: [_jsxs("label", { style: { ...S.eyebrow }, children: ["City", _jsx("input", { value: relocCity, onChange: (e) => setRelocCity(e.target.value), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Team Name", _jsx("input", { value: relocName, onChange: (e) => setRelocName(e.target.value), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Abbr (3 chars)", _jsx("input", { value: relocAbbr, onChange: (e) => setRelocAbbr(e.target.value.toUpperCase().slice(0, 3)), style: { width: '100%', padding: 4, fontFamily: 'inherit', border: `1px solid ${COLORS.ink}` } })] }), _jsxs("label", { style: { ...S.eyebrow }, children: ["Color", _jsx("input", { type: "color", value: relocColor, onChange: (e) => setRelocColor(e.target.value), style: { width: '100%', padding: 0, height: 30, border: `1px solid ${COLORS.ink}` } })] }), _jsx("button", { onClick: () => {
                                    const r = relocateAction({ city: relocCity, name: relocName, abbr: relocAbbr, color: relocColor });
                                    alert(r.ok ? `Welcome to ${relocCity}!` : (r.reason || 'Failed'));
                                }, style: { ...S.radioBtn(true), background: COLORS.gold, borderColor: COLORS.gold, gridColumn: '1 / -1' }, children: "Move + Rebrand ($500M fee)" })] }))] })] }));
}
